In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('./Input/ME_Analysis.xlsx',sheet_name='Sheet1')

In [5]:
df.head()

,CalendarMonthStart,Editorial Language,Issues,EditorialCountryName,ComponentName,QueueCategory,QueueCategory1,QueueCategory2,Country&Lang,Country&Lang(T/F),Only Country,Only Lang
0,20160101,(blank),1,Australia,Appeals,NQP,AQ,NaN,Australia(blank),NaN,NaN,NaN
1,20160101,(blank),59,China,Appeals,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
2,20160101,(blank),5,China,Complaints,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
3,20160101,(blank),1,China,Policy Questions,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
4,20160101,(blank),1,France,Appeals,NQP,AQ,NaN,France(blank),NaN,NaN,NaN

In [11]:
g = df.groupby(['CalendarMonthStart'])['Issues']

In [14]:
def convert_dt_int_to_dt(dt_int_):
    return datetime.strptime(str(dt_int_),'%Y%m%d')

In [15]:
df.CalendarMonthStart.map()

,CalendarMonthStart,Editorial Language,Issues,EditorialCountryName,ComponentName,QueueCategory,QueueCategory1,QueueCategory2,Country&Lang,Country&Lang(T/F),Only Country,Only Lang
0,20160101,(blank),1,Australia,Appeals,NQP,AQ,NaN,Australia(blank),NaN,NaN,NaN
1,20160101,(blank),59,China,Appeals,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
2,20160101,(blank),5,China,Complaints,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
3,20160101,(blank),1,China,Policy Questions,NQP,AQ,NaN,China(blank),NaN,NaN,NaN
4,20160101,(blank),1,France,Appeals,NQP,AQ,NaN,France(blank),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
29877,20210601,Croatian,2,Croatia,Appeals,NQP,AQ,NaN,CroatiaCroatian,CroatiaCroatian,Croatia,Croatian
29878,20210601,Croatian,1,Croatia,Complaints,NQP,AQ,NaN,CroatiaCroatian,CroatiaCroatian,Croatia,Croatian
29879,20210401,Bulgarian,1,Bulgaria,Appeals,NQP,AQ,NaN,BulgariaBulgarian,BulgariaBulgarian,Bulgaria,Bulgarian
29880,20210601,Bulgarian,2,Bulgaria,Appeals,NQP,AQ,NaN,BulgariaBulgarian,BulgariaBulgarian,Bulgaria,Bulgarian
29881,20210301,Albanian,1,Albania,Complaints,NQP,AQ,NaN,AlbaniaAlbanian,AlbaniaAlbanian,Albania,Albanian